rentalWebpage/config/routes.rb
Rails.application.routes.draw do

  get 'property_listing/property_listing'
  get 'logins/index'
  
  post '/rate' => 'rater#create', :as => 'rate'

  resources :properties do
    resources :reviews do
      member do
        put "helpful", to: "reviews#helpful"
      end
    end
  end
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "/addReview", controller: 'reviews', action: 'addReview', as: 'addReview'

  root controller: 'home', action: 'index'

end

rentalWebpage/app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

rentalWebpage/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :reviews
end

rentalWebpage/app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

rentalWebpage/app/models/property.rb
class Property < ActiveRecord::Base
  has_many :reviews
  validates_presence_of :address, :city, :state, :zipcode, :message => "is required to continue"
  validates_numericality_of :zipcode, :message => "must be numberic"
  ratyrate_rateable 'property_rating'
end

rentalWebpage/app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

rentalWebpage/app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

rentalWebpage/app/models/reply.rb
class Reply < ActiveRecord::Base
  field :reply, :type => String
  belongs_to :property
  
end

rentalWebpage/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :property
  belongs_to :user
end

rentalWebpage/app/models/user.rb
class User < ActiveRecord::Base

  ratyrate_rater
  
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|

      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

rentalWebpage/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.includes(:reviews).order('reviews.created_at').limit(10).reverse
  end
end

rentalWebpage/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  end
end

rentalWebpage/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully added!' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated!' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully deelted!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:address, :apartment, :city, :state, :zipcode, :rooms, :bathrooms)
    end
end

rentalWebpage/app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if current_user
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

rentalWebpage/app/controllers/reply_controller.rb
def show
  @reply = Reply.find(params[:id])
  
  respond_to do |format|
    format.html #show.html.erb
    format.json {render :json => @reply}
  end
end
    |

rentalWebpage/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @property = Property.find(params[:property_id])
    @review = @property.reviews.create(review_params)
    redirect_to property_path(@property)
  end
 
  def helpful
    @property = Property.find(params[:property_id])
    @review = @property.reviews.find(params[:id])      
    if @review.helpful_total.nil? || @review.helpful_total == 0
      @review.helpful_total = 1 
    else
      @review.helpful_total = @review.helpful_total + 1        
    end
    @review.save
    redirect_to @property 
  end

  private
    def review_params
      params.require(:review).permit(:review, :helpful_total)
    end

    def addReview

    end
  
end

rentalWebpage/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

rentalWebpage/app/helpers/add_properties_helper.rb
module AddPropertiesHelper
end

rentalWebpage/app/helpers/application_helper.rb
module ApplicationHelper
end

rentalWebpage/app/helpers/home_helper.rb
module HomeHelper
end

rentalWebpage/app/helpers/logins_helper.rb
module LoginsHelper
end

rentalWebpage/app/helpers/review_helper.rb
module ReviewHelper
end

rentalWebpage/app/helpers/sessions_helper.rb
module SessionsHelper
end

rentalWebpage/app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2>Oh no! There are <%= pluralize(@property.errors.count, "error") %>! Please resolve and try again:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address, "Address:" %><br>
    <%= f.text_field :address %>
    <%=" (required)" %>
  </div>
  <div class="field">
    <%= f.label :apartment, "Apt/Unit/Suite" %><br>
    <%= f.text_field :apartment %>
  </div>
  <div class="field">
    <%= f.label :city, "City:" %><br>
    <%= f.text_field :city %>
    <%=" (required)" %>
  </div>
  <div class="field">
    <%= f.label :state, "State:" %><br>
    <%= f.select(:state, ["WI"]) %>
    <%=" (required)" %>
  </div>
  <div class="field">
    <%= f.label :zipcode, "Zipcode:" %><br>
    <%= f.text_field :zipcode %>
    <%=" (required)" %>
  </div>
  <div class="field">
    <%= f.label :rooms, "Number of Bedrooms:" %><br>
    <%= f.number_field :rooms %>
  </div>
  <div class="field">
    <%= f.label :bathrooms, "Number of Bathrooms:" %><br>
    <%= f.number_field :bathrooms %>
  </div>
  <div class="actions">
    <% if @property.id.nil? %>
      <%= f.submit "Add Property" %>
    <% else %>
      <%= f.submit "Update Property"%>
    <% end %>
  </div>
<% end %>

rentalWebpage/app/views/properties/edit.html.erb
<p><strong>Edit Property</strong></p>

<%= render 'form' %>

<!-- May be used later <%= link_to 'Back to Properties', properties_path %> | -->
<strong><%= link_to 'Home', root_path %></strong> |
<strong><%= link_to 'Add New Property', new_property_path %></strong>

rentalWebpage/app/views/properties/index.html.erb
<p><strong>Properties</strong></p>

<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.address + " " + property.apartment %></td>
      </tr>
      <tr>
        <td><%= property.city + ", " + property.state + " "  + property.zipcode %></td>
      </tr>
      <tr>
        <td><b>Number of Bedrooms: </b><%= property.rooms %></td>
      </tr>
      <tr>
        <td><b>Number of Bathrooms: </b><%= property.bathrooms %></td>
      </tr>
      <tr>
        <td><%= link_to 'More Details', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Delete', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<strong><%= link_to 'Home', root_path %></strong>  |
<strong><%= link_to 'Add New Property', new_property_path %></strong>

rentalWebpage/app/views/properties/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <h3>Add New Rentral Property</h3>

    <%= render 'form' %>
  </div>
  <div class="col-sm-6">
    <h3>Instructions</h3>
    <p>Please complete this form to add a new property.</p>
    <p>Once you have added the property,
    <p>you will be given the option to add a review!</p>
    <br>
    <br>
    <p>Thank you for using Rental Property Listing!</p>
  </div>
</div>
<strong><%= link_to 'Home', root_path %></strong>

rentalWebpage/app/views/properties/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <h3>Property Details</h3>
    <br>
    <p><strong>Address</strong><p>
    <p>
      <%= @property.address + " " + @property.apartment %>
    </p>

    <p>
      <%= @property.city + ", " + @property.state + " " + @property.zipcode %>
    </p>
    <br>
    <p>
      <strong>Bedrooms:</strong>
      <%= @property.rooms %>
    </p>

    <p>
      <strong>Bathrooms:</strong>
      <%= @property.bathrooms %>
    </p>
  </div>
  <div class="col-sm-6">
    <h3>Property Reviews</h3>

    <% @property.reviews.each do |review| %> 
      <div id = "review">
        <p>
        <em><%= review.created_at.to_date %><br></em>
        <%= review.review %>
      </p>

      <input type="button" value="Like" onclick="alert('Thumbs Up!')">
      <input type="button" value="Dislike" onclick="alert('Thumbs Down!')">
 <input type="button" value="Reply"
    </div>
    <% end %>

    <h3>Add a new review</h3>
      <% if !current_user %>
          <%= form_for([@property, @property.reviews.build]) do |f| %>
      <div>Property Rating: <%= rating_for @property, "property_rating" %></div>
        <p>
          <%= f.label :review %><br>
          <%= f.text_area :review %>
          <%=form_for(@reply, :action=> "update") do |f| %>
        </p>
        <p>
          <%= f.submit %>
        </p>
        <% end %>
      <% else %>
        <p><strong>Please sign in to review this property!</strong></p>
    <% end %>
  </div>
</div>


<strong><%= link_to 'Home', root_path %></strong> |
<!-- <strong><%= link_to 'Edit', edit_property_path(@property) %></strong> | ***Disabled*** --->
<strong><%= link_to 'Add New Property', new_property_path %></strong>