rentalWebpage/config/routes.rb
Rails.application.routes.draw do

  get 'property_listing/property_listing'
  get 'logins/index'
  
  post '/rate' => 'rater#create', :as => 'rate'

  resources :properties do
    resources :reviews do
      member do
        put "helpful", to: "reviews#helpful"
      end
    end
  end
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get "/addReview", controller: 'reviews', action: 'addReview', as: 'addReview'

  root controller: 'home', action: 'index'

end

rentalWebpage/app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

rentalWebpage/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :reviews
end

rentalWebpage/app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

rentalWebpage/app/models/property.rb
class Property < ActiveRecord::Base
  has_many :reviews
  validates_presence_of :address, :city, :state, :zipcode, :message => "is required to continue"
  validates_numericality_of :zipcode, :message => "must be numberic"
  ratyrate_rateable 'property_rating'
end

rentalWebpage/app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

rentalWebpage/app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

rentalWebpage/app/models/reply.rb
class Reply < ActiveRecord::Base
  field :reply, :type => String
  belongs_to :property
  
end

rentalWebpage/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :property
  belongs_to :user
end

rentalWebpage/app/models/user.rb
class User < ActiveRecord::Base

  ratyrate_rater
  
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|

      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

rentalWebpage/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.includes(:reviews).order('reviews.created_at').limit(10).reverse
  end
end

rentalWebpage/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  end
end

rentalWebpage/app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if current_user
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

rentalWebpage/app/controllers/reply_controller.rb
def show
  @reply = Reply.find(params[:id])
  
  respond_to do |format|
    format.html #show.html.erb
    format.json {render :json => @reply}
  end
end
    |

rentalWebpage/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @property = Property.find(params[:property_id])
    @review = @property.reviews.create(review_params)
    redirect_to property_path(@property)
  end
 
  def helpful
    @property = Property.find(params[:property_id])
    @review = @property.reviews.find(params[:id])      
    if @review.helpful_total.nil? || @review.helpful_total == 0
      @review.helpful_total = 1 
    else
      @review.helpful_total = @review.helpful_total + 1        
    end
    @review.save
    redirect_to @property 
  end

  private
    def review_params
      params.require(:review).permit(:review, :helpful_total)
    end

    def addReview

    end
  
end

rentalWebpage/app/helpers/add_properties_helper.rb
module AddPropertiesHelper
end

rentalWebpage/app/helpers/application_helper.rb
module ApplicationHelper
end

rentalWebpage/app/helpers/home_helper.rb
module HomeHelper
end

rentalWebpage/app/helpers/logins_helper.rb
module LoginsHelper
end

rentalWebpage/app/helpers/review_helper.rb
module ReviewHelper
end

rentalWebpage/app/helpers/sessions_helper.rb
module SessionsHelper
end

rentalWebpage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rental Property Listing</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </head>
   
  <div class="row">
    <div class="col-sm-12">
      <div class="container">
        <header>
          <h1>Rental Property Listing</h1>
        </header>
        
        <div id="user-widget">
          <% if current_user %>
            Welcome <strong><%= current_user.name %></strong>!
            <%= link_to "Sign out", signout_path, id: "sign_out" %>
          <% else %>
            <%= link_to "Sign in as Student", "/auth/facebook", id: "sign_in" %>
            or
            <%= link_to "Sign in as Landlord", logins_index_path %>
          <% end %>
        </div>
        <br>
        <%= form_tag property_listing_property_listing_path, :method => 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          </p>
        <% end %>
        
        <p><strong><%= flash[:notice] %></strong></p>
        
        <section class="content">
          <%= yield %>
        </section>
        <footer>
          <h5>&copy;<%=Date.today.year %> Rental Property Listing</h5>
        </footer>
      </div>
    </div>
  </div>
</html>